"""add poc and dashboard models

Revision ID: ddceb963fe87
Revises: 1d9d32c2d30f
Create Date: 2026-08-14 11:48:52.779486
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision = 'ddceb963fe87'
down_revision = '1d9d32c2d30f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tag',
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('vendor',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('homepage', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('vuln',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vuln_cve_id'), 'vuln', ['cve_id'], unique=True)
    op.create_index(op.f('ix_vuln_severity'), 'vuln', ['severity'], unique=False)
    op.create_table('product',
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('homepage', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sqlite.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('component',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('poc',
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra_meta', sqlite.JSON(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poc_content_hash'), 'poc', ['content_hash'], unique=False)
    op.create_index(op.f('ix_poc_format'), 'poc', ['format'], unique=False)
    op.create_index(op.f('ix_poc_name'), 'poc', ['name'], unique=False)
    op.create_index(op.f('ix_poc_severity'), 'poc', ['severity'], unique=False)
    op.create_index(op.f('ix_poc_source'), 'poc', ['source'], unique=False)
    op.create_index(op.f('ix_poc_status'), 'poc', ['status'], unique=False)
    op.create_index(op.f('ix_poc_uuid'), 'poc', ['uuid'], unique=True)
    op.create_table('poc_affected',
    sa.Column('poc_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('component_id', sa.BigInteger(), nullable=True),
    sa.Column('version_start', sa.String(length=32), nullable=True),
    sa.Column('version_start_type', sa.String(length=8), nullable=False),
    sa.Column('version_end', sa.String(length=32), nullable=True),
    sa.Column('version_end_type', sa.String(length=8), nullable=False),
    sa.Column('version_expression', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['poc_id'], ['poc.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poc_affected_poc_id'), 'poc_affected', ['poc_id'], unique=False)
    op.create_table('poc_attachment',
    sa.Column('poc_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['poc_id'], ['poc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poc_attachment_poc_id'), 'poc_attachment', ['poc_id'], unique=False)
    op.create_table('poc_category',
    sa.Column('poc_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['poc_id'], ['poc.id'], ),
    sa.PrimaryKeyConstraint('poc_id', 'category_id')
    )
    op.create_table('poc_deployment',
    sa.Column('poc_id', sa.BigInteger(), nullable=False),
    sa.Column('attack_vector', sa.String(length=32), nullable=True),
    sa.Column('auth_required', sa.Boolean(), nullable=True),
    sa.Column('auth_role', sa.String(length=32), nullable=True),
    sa.Column('protocol', sa.String(length=32), nullable=True),
    sa.Column('default_port', sa.Integer(), nullable=True),
    sa.Column('requires_interaction', sa.Boolean(), nullable=True),
    sa.Column('safe_to_run', sa.Boolean(), nullable=True),
    sa.Column('extra_meta', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['poc_id'], ['poc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poc_id')
    )
    op.create_table('poc_source_record',
    sa.Column('poc_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=3), nullable=True),
    sa.Column('extra_meta', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['poc_id'], ['poc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poc_source_record_batch_id'), 'poc_source_record', ['batch_id'], unique=False)
    op.create_index(op.f('ix_poc_source_record_poc_id'), 'poc_source_record', ['poc_id'], unique=False)
    op.create_table('poc_tag',
    sa.Column('poc_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['poc_id'], ['poc.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('poc_id', 'tag_id')
    )
    op.create_table('poc_version',
    sa.Column('poc_id', sa.BigInteger(), nullable=False),
    sa.Column('version_seq', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=3), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['poc_id'], ['poc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poc_version_poc_id'), 'poc_version', ['poc_id'], unique=False)
    op.create_table('poc_vuln',
    sa.Column('poc_id', sa.BigInteger(), nullable=False),
    sa.Column('vuln_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['poc_id'], ['poc.id'], ),
    sa.ForeignKeyConstraint(['vuln_id'], ['vuln.id'], ),
    sa.PrimaryKeyConstraint('poc_id', 'vuln_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poc_vuln')
    op.drop_index(op.f('ix_poc_version_poc_id'), table_name='poc_version')
    op.drop_table('poc_version')
    op.drop_table('poc_tag')
    op.drop_index(op.f('ix_poc_source_record_poc_id'), table_name='poc_source_record')
    op.drop_index(op.f('ix_poc_source_record_batch_id'), table_name='poc_source_record')
    op.drop_table('poc_source_record')
    op.drop_table('poc_deployment')
    op.drop_table('poc_category')
    op.drop_index(op.f('ix_poc_attachment_poc_id'), table_name='poc_attachment')
    op.drop_table('poc_attachment')
    op.drop_index(op.f('ix_poc_affected_poc_id'), table_name='poc_affected')
    op.drop_table('poc_affected')
    op.drop_index(op.f('ix_poc_uuid'), table_name='poc')
    op.drop_index(op.f('ix_poc_status'), table_name='poc')
    op.drop_index(op.f('ix_poc_source'), table_name='poc')
    op.drop_index(op.f('ix_poc_severity'), table_name='poc')
    op.drop_index(op.f('ix_poc_name'), table_name='poc')
    op.drop_index(op.f('ix_poc_format'), table_name='poc')
    op.drop_index(op.f('ix_poc_content_hash'), table_name='poc')
    op.drop_table('poc')
    op.drop_table('component')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('product')
    op.drop_index(op.f('ix_vuln_severity'), table_name='vuln')
    op.drop_index(op.f('ix_vuln_cve_id'), table_name='vuln')
    op.drop_table('vuln')
    op.drop_table('vendor')
    op.drop_table('tag')
    op.drop_table('category')
    # ### end Alembic commands ###